---
- hosts: all
  become: true
  tasks:
  #- name: update distibution
   # apt:
    #  update_cache: yes
  #- name: install git
   # apt:
    #  name:
     #   - git
      #  - nodejs
       # - npm
      #update_cache: yes
  
  - name: install apache2
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: file configuration copy
    copy: 
      src: index.html 
      dest: /var/www/html
      owner: root
      group: root
      mode: u+rw,g=r,o=r
  - name: launch apache2
    service:
        name: apache2
        state: started
        enabled: yes