---
- hosts: all
  become: true
  tasks:
  #- name: update distibution
   # apt:
    #  update_cache: yes
  #- name: install git
   # apt:
    #  name:
     #   - git
      #  - nodejs
       # - npm
      #update_cache: yes
  
#  - name: install apache2
#   apt:
#     name: apache2
#     state: present
#     update_cache: yes
# - name: file configuration copy
#   copy: 
#     src: index.html 
#     dest: /var/www/html
#     owner: root
#     group: root
#     mode: u+rw,g=r,o=r
# - name: launch apache2
#   service:
#       name: apache2
#       state: started
#       enabled: yes
  - name: Update the apt package index
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: Install packages for apt add repository over HTTPS
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
  - name: Add Apt signing key from official docker repo
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: add docker official repository for Debian Stretch
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present
  - name: Index new repo into the cache
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: actually install docker
    apt:
      name: "docker-ce"
      state: latest

  - name: copier les sources des projets result
    copy: 
      src: result 
      dest: /TPDocker
    
  - name: copier les sources des projets vote 
    copy:
      src: vote  
      dest: /TPDocker

  - name: copier les sources des projets worker
    copy:
      src: worker
      dest: /TPDocker

  - name: build docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: build l'image result
    command: docker build -t image_result /TPDocker/result 

  - name: build l'image vote
    command: docker build -t image_vote /TPDocker/vote

  - name: build l'image worker
    command: docker build -t image_worker /TPDocker/worker  

  - name: Suppresion des sources
    file:
      state: absent
      path: ./TPDocker
  